var mode = q('mode'); // 'default','flowey','beta' 
var dialog = q('dialog'); // 'enabled','disabled','true','false','on','off','yes','no','1','0'
var textcolor = q('textcolor'); // (css code)
var textfont = q('textfont'); // (font name),'sans-seriff','comic-sans','papyrus','wingdings'
var username = q('username'); // (username)
var user = q('user'); // (username)
var keycode = q('keycode'); // (keycode)
var key = q('key'); // (keycode)
var code = q('code'); // (unlock code)
var refer = q('refer'); // (referal code)
